### ISSUE TITLE
Ping command crash inside snap

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni-user/CBJ_Hub_Snap#2]
As I have written in [this post](https://forum.snapcraft.io/t/request-auto-connect-firewall-control-or-network-control-or-network-observe-for-cbj-hub/31222) snap with ping command crash.
I am getting an error `ProcessException: Permission denied` for the command pin.

Program Crash Log:

```dart
  Check that /usr/bin/timeout exists
    command: timeout 2s avahi-browse --all -p
  Check that /usr/bin/timeout exists
    command: timeout 2s mdns-scan
You can make the mdns process better by installing `mdns-scan`
Unhandled exception:
ProcessException: Permission denied
  Command: ping -O -n -W 1 -i 1 -t 255 -c 1 192.168.31.1
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      BasePing.platformProcess (package:dart_ping/src/ping/base_ping.dart:71)
#3      BasePing._onListen (package:dart_ping/src/ping/base_ping.dart:86)
#4      _runGuarded (dart:async/stream_controller.dart:814)
#5      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:692)
#6      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:417)
#7      _StreamController._subscribe (dart:async/stream_controller.dart:691)
#8      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827)
#9      _StreamImpl.listen (dart:async/stream_impl.dart:473)
#10     _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:1028)
#11     _StreamIterator.moveNext (dart:async/stream_impl.dart:1004)
#12     HostScanner._getHostFromPing (package:network_tools/src/host_scanner.dart)
#13     HostScanner.getAllPingableDevices (package:network_tools/src/host_scanner.dart:41)
<asynchronous suspension>
```

Snap Permission Log:

```
:~$ snappy-debug.security scanlog
INFO: Following '/var/log/syslog'. If have dropped messages, use:
INFO: $ sudo journalctl --output=short --follow --all | sudo snappy-debug
= AppArmor =
Time: Aug  9 22:13:59
Log: apparmor="DENIED" operation="open" profile="snap.cbj-hub.cbj-hub" name="/etc/" pid=11461 comm="DartWorker" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /etc/ (read)
Suggestions:
* adjust program to read necessary files from $SNAP, $SNAP_DATA, $SNAP_COMMON, $SNAP_USER_DATA or $SNAP_USER_COMMON
* adjust snap to use snap layouts (https://forum.snapcraft.io/t/snap-layouts/7207)

= AppArmor =
Time: Aug  9 22:13:59
Log: apparmor="DENIED" operation="open" profile="snap.cbj-hub.cbj-hub" name="/usr/bin/timeout" pid=11513 comm="DartWorker" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /usr/bin/timeout (read)
Suggestions:
* adjust snap to ship 'timeout'
* adjust program to use relative paths if the snap already ships 'timeout'

= AppArmor =
Time: Aug  9 22:13:59
Log: apparmor="DENIED" operation="open" profile="snap.cbj-hub.cbj-hub" name="/usr/bin/timeout" pid=11515 comm="DartWorker" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
File: /usr/bin/timeout (read)
Suggestions:
* adjust snap to ship 'timeout'
* adjust program to use relative paths if the snap already ships 'timeout'

= AppArmor =
Time: Aug  9 22:13:59
Log: apparmor="DENIED" operation="exec" profile="snap.cbj-hub.cbj-hub" name="/usr/bin/ping" pid=11543 comm="DartWorker" requested_mask="x" denied_mask="x" fsuid=0 ouid=0
File: /usr/bin/ping (exec)
Suggestions:
* adjust snap to ship 'ping'
* adjust program to use relative paths if the snap already ships 'ping'
* add one of 'firewall-control, network-control, network-observe' to 'plugs'
```

The ping command is required in order to find devices in the network, for example Tasmota devices which does not publish themselves under mdns.

**Comment by guyluz11** [comment]
Error while trying to run the code in snap with  ```grade: stable        confinement: strict```  and change ping to start from IP 2 instead of 1


``` dart
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: Unhandled exception:
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: ProcessException:
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]:   Command: ping -O -n -W 1 -i 1 -t 255 -c 1 192.168.31.204
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #1      Process.start (dart:io-patch/process_patch.dart:38)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #2      BasePing.platformProcess (package:dart_ping/src/ping/base_ping.dart:71)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #3      BasePing._onListen (package:dart_ping/src/ping/base_ping.dart:86)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #4      _runGuarded (dart:async/stream_controller.dart:814)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #5      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:692)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #6      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:415)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #7      _StreamController._subscribe (dart:async/stream_controller.dart:691)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #8      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #9      _StreamImpl.listen (dart:async/stream_impl.dart:471)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #10     _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:942)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #11     _StreamIterator.moveNext (dart:async/stream_impl.dart:918)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #12     HostScanner._getHostFromPing (package:network_tools/src/host_scanner.dart)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #13     HostScanner.getAllPingableDevices (package:network_tools/src/host_scanner.dart:41)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: <asynchronous suspension>
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: #14     CompaniesConnectorConjector.searchPingableDevicesAndSetThemUpByHostName (package:cbj_hub/infrastructure/devices/companies_connector_conjector.dart:258)
2022-09-29T16:49:52+03:00 cbj-hub.cbj-hub[38078]: <asynchronous suspension>
2022-09-29T16:49:52+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Main process exited, code=exited, status=255/EXCEPTION
2022-09-29T16:49:52+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-09-29T16:49:52+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Scheduled restart job, restart counter is at 6.
2022-09-29T16:49:52+03:00 systemd[1]: Stopped Service for snap application cbj-hub.cbj-hub.
2022-09-29T16:49:52+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Start request repeated too quickly.
2022-09-29T16:49:52+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-09-29T16:49:52+03:00 systemd[1]: Failed to start Service for snap application cbj-hub.cbj-hub.

```









Error while trying to run the code in snap with  ```grade: devel        confinement: devmode```  and change ping to start from IP 2 instead of 1


``` dart
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: Unhandled exception:
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: ProcessException:
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]:   Command: ping -O -n -W 1 -i 1 -t 255 -c 1 192.168.31.199
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #1      Process.start (dart:io-patch/process_patch.dart:38)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #2      BasePing.platformProcess (package:dart_ping/src/ping/base_ping.dart:71)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #3      BasePing._onListen (package:dart_ping/src/ping/base_ping.dart:86)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #4      _runGuarded (dart:async/stream_controller.dart:814)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #5      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:692)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #6      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:415)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #7      _StreamController._subscribe (dart:async/stream_controller.dart:691)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #8      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #9      _StreamImpl.listen (dart:async/stream_impl.dart:471)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #10     _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:942)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #11     _StreamIterator.moveNext (dart:async/stream_impl.dart:918)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #12     HostScanner._getHostFromPing (package:network_tools/src/host_scanner.dart)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #13     HostScanner.getAllPingableDevices (package:network_tools/src/host_scanner.dart:41)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: <asynchronous suspension>
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: #14     CompaniesConnectorConjector.searchPingableDevicesAndSetThemUpByHostName (package:cbj_hub/infrastructure/devices/companies_connector_conjector.dart:258)
2022-09-29T17:05:13+03:00 cbj-hub.cbj-hub[41557]: <asynchronous suspension>
2022-09-29T17:05:13+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Main process exited, code=exited, status=255/EXCEPTION
2022-09-29T17:05:13+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-09-29T17:05:13+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Scheduled restart job, restart counter is at 6.
2022-09-29T17:05:13+03:00 systemd[1]: Stopped Service for snap application cbj-hub.cbj-hub.
2022-09-29T17:05:13+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Start request repeated too quickly.
2022-09-29T17:05:13+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-09-29T17:05:13+03:00 systemd[1]: Failed to start Service for snap application cbj-hub.cbj-hub.
```

**Comment by guyluz11** [comment]
When using IP range 2 to 100 and getting results not in ascending order the program works great.

Tested again using results not in ascending order without any IP range I am getting a different error.

```dart
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: Unhandled exception:
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: ProcessException: Failed to start ping. OS returned an error (code 24) which can't be fully converted to Dart string (Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.): ?6??
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]:   Command: ping -O -n -W 1 -i 1 -t 255 -c 1 192.168.31.213
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #1      Process.start (dart:io-patch/process_patch.dart:38)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #2      BasePing.platformProcess (package:dart_ping/src/ping/base_ping.dart:71)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #3      BasePing._onListen (package:dart_ping/src/ping/base_ping.dart:86)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #4      _runGuarded (dart:async/stream_controller.dart:814)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #5      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:692)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #6      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:415)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #7      _StreamController._subscribe (dart:async/stream_controller.dart:691)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #8      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #9      _StreamImpl.listen (dart:async/stream_impl.dart:471)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #10     _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:942)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #11     _StreamIterator.moveNext (dart:async/stream_impl.dart:918)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #12     HostScanner._getHostFromPing (package:network_tools/src/host_scanner.dart)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #13     HostScanner.getAllPingableDevices (package:network_tools/src/host_scanner.dart:41)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: <asynchronous suspension>
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: #14     CompaniesConnectorConjector.searchPingableDevicesAndSetThemUpByHostName (package:cbj_hub/infrastructure/devices/companies_connector_conjector.dart:262)
2022-09-29T19:43:31+03:00 cbj-hub.cbj-hub[62529]: <asynchronous suspension>
2022-09-29T19:43:31+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Main process exited, code=exited, status=255/EXCEPTION
2022-09-29T19:43:31+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-09-29T19:43:31+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Scheduled restart job, restart counter is at 5.
2022-09-29T19:43:31+03:00 systemd[1]: Stopped Service for snap application cbj-hub.cbj-hub.
2022-09-29T19:43:31+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Start request repeated too quickly.
2022-09-29T19:43:31+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-09-29T19:43:31+03:00 systemd[1]: Failed to start Service for snap application cbj-hub.cbj-hub.

```

Maybe the next run with changes will completely fix the issue, next run will ping each subnet and will not start the next subnet pinging before the first one completes.

**Comment by guyluz11** [comment]
Did that
> Maybe the next run with changes will completely fix the issue, next run will ping each subnet and will not start the next subnet pinging before the first one completes.

 as long as splitting ping request to 1-126 and after that ends 127-254 and ping command it is working inside snap.

Horray 🎉🎉🎉

**Comment by guyluz11** [comment]
It is back, now I think the error is consistent

```dart
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: Unhandled exception:
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: ProcessException: Permission denied
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]:   Command: ping -O -n -W 1 -i 1 -t 255 -c 1 192.168.31.1
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #1      Process.start (dart:io-patch/process_patch.dart:38)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #2      BasePing.platformProcess (package:dart_ping/src/ping/base_ping.dart:71)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #3      BasePing._onListen (package:dart_ping/src/ping/base_ping.dart:86)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #4      _runGuarded (dart:async/stream_controller.dart:814)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #5      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:692)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #6      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:415)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #7      _StreamController._subscribe (dart:async/stream_controller.dart:691)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #8      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #9      _StreamImpl.listen (dart:async/stream_impl.dart:471)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #10     _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:942)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #11     _StreamIterator.moveNext (dart:async/stream_impl.dart:918)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #12     HostScanner._getHostFromPing (package:network_tools/src/host_scanner.dart)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #13     HostScanner.getAllPingableDevices (package:network_tools/src/host_scanner.dart:41)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: <asynchronous suspension>
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: #14     CompaniesConnectorConjector.searchPingableDevicesAndSetThemUpByHostName (package:cbj_hub/infrastructure/devices/companies_connector_conjector.dart:251)
2022-10-01T10:15:37+03:00 cbj-hub.cbj-hub[11160]: <asynchronous suspension>
2022-10-01T10:15:37+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Main process exited, code=exited, status=255/EXCEPTION
2022-10-01T10:15:37+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-10-01T10:15:37+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Scheduled restart job, restart counter is at 5.
2022-10-01T10:15:37+03:00 systemd[1]: Stopped Service for snap application cbj-hub.cbj-hub.
2022-10-01T10:15:37+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Start request repeated too quickly.
2022-10-01T10:15:37+03:00 systemd[1]: snap.cbj-hub.cbj-hub.service: Failed with result 'exit-code'.
2022-10-01T10:15:37+03:00 systemd[1]: Failed to start Service for snap application cbj-hub.cbj-hub.

```

**Comment by guyluz11** [comment]
Adding `iputils-ping` to `stage-packages:` worked

**Comment by CyBear-Jinni-user** [comment]
Added Hacktoberfest support after the last commit, I am hoping it will still count.
